version: '2.1'
services:
  localstack:
    depends_on:
      - postgres
    container_name: "localstack-image"
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4571:4571"
      - "8082:8082"
    environment:
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${LOCALSTACK_VOLUME_DIR}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  postgres:
    container_name: "postgres"
    image: postgres:13.2-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./sql:/docker-entrypoint-initdb.d/"